vstemplates/Template.AspNetCore.RazorPages/Models/HomeViewModel.cs
using System.ComponentModel.DataAnnotations;
using Template.AspNetCore.RazorPages.DataAnnotations;

namespace Template.AspNetCore.RazorPages.Models
{
    public class HomeViewModel
    {
        [Display(Name = StringsModelKeys.Form.Username)]
        [OnlyAlphanumeric]
        [Required(ErrorMessageResourceType = typeof(StringsModel.ValidationErrors), ErrorMessageResourceName = "FieldIsRequired")]
        public string Username { get; set; }

        [Display(Name = StringsModelKeys.Form.Name)]
        [Required(ErrorMessageResourceType = typeof(StringsModel.ValidationErrors), ErrorMessageResourceName = "FieldIsRequired")]
        public string Name { get; set; }

        [Display(Name = StringsModelKeys.Form.Surname)]
        [Required(ErrorMessageResourceType = typeof(StringsModel.ValidationErrors), ErrorMessageResourceName = "FieldIsRequired")]
        public string Surname { get; set; }

        public string GetWelcomeMessage()
        {
            // LHQ: Returns localized text with input parameters
            return StringsModel.Messages.WelcomeMessage(Name, Surname, Username);
        }
    }
}

vstemplates/Template.AspNetCore.RazorPages/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Template.AspNetCore.RazorPages.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

vstemplates/Template.AspNetCore.RazorPages/Pages/Index.cshtml.cs
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Template.AspNetCore.RazorPages.Models;

namespace Template.AspNetCore.RazorPages.Pages
{
    public class IndexModel : PageModel
    {
        public string GetWelcomeMessage()
        {
            // LHQ: Returns localized text with input parameters
            return StringsModel.Messages.WelcomeMessage(Model.Name, Model.Surname, Model.Username);
        }

        public IActionResult OnGet(string userName, string name, string surname)
        {
            Model = new HomeViewModel
            {
                Username = userName,
                Name = name,
                Surname = surname
            };
            return Page();
        }

        public IActionResult OnGetSetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }

        [BindProperty]
        public HomeViewModel Model { get; set; }

        public bool HasSubmitData
        {
            get
            {
                return Model != null && (!string.IsNullOrEmpty(Model.Name) || !string.IsNullOrEmpty(Model.Surname));
            }
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                return RedirectToPage(new
                {
                    userName = Model.Username,
                    name = Model.Name,
                    surname = Model.Surname
                });
            }

            Model = new HomeViewModel();
            return Page();
        }
    }
}

vstemplates/Template.AspNetCore.RazorPages/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Template.AspNetCore.RazorPages.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

vstemplates/Template.AspNetCore.RazorPages/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Template.AspNetCore.RazorPages</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Template.AspNetCore.RazorPages</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Html.PartialAsync("_SelectLanguagePartial")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Template.AspNetCore.RazorPages
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

vstemplates/Template.AspNetCore.RazorPages/Pages/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Http.Extensions
@inject IStringLocalizer stringLocalizer
@{
    string currentPathAndQuery = this.Context.Request.GetEncodedPathAndQuery();
}

<ul class="flex-grow-1" id="languages">
    @foreach (var culture in @StringsModel.AvailableCultures)
    {
        string langResourceKey = nameof(StringsModelKeys.Languages) + culture;
        <li>
            <a asp-page="Index" asp-page-handler="SetLanguage" asp-route-culture="@culture"
               asp-route-returnUrl="@currentPathAndQuery">
                @stringLocalizer[langResourceKey]
            </a>
        </li>
    }
</ul>